### ISSUE TITLE
Is there way to get coupon code details using useCheckoutPricing hook?

### ISSUE THREAD

**Issue by ashokdudhade-cbs** [recurly/react-recurly#107]
_Warning_: Github issues are not an official support channel for Recurly. If you have an urgent request we suggest you contact us through an official channel: support@recurly.com or https://recurly.zendesk.com

We would want to display coupon code details in checkout process. Is there a way we can fetch coupon code name, trial details, duration etc. from useCheckoutPricing react hook.

**Comment by chrissrogers** [comment]
It's possible to get some coupon details from the [`recurly.coupon`](https://github.com/recurly/recurly-js/blob/master/lib/recurly/coupon.js#L19) method. Use the `useRecurly` hook to get your `recurly` instance, and call `recurly.coupon` from there. Your callback will be called with a signature of `(coupon, err)`, where the coupon will be in the form of something like these fixtures: https://github.com/recurly/recurly-js/tree/master/test/server/fixtures/coupons
