### ISSUE TITLE
Is there a way to set font smoothing?

### ISSUE THREAD

**Issue by aialec90** [recurly/react-recurly#109]
Hi,

I don't see a way to set `-webkit-font-smoothing: antialiased;` on input element or whole body. Is there a way? 

Tried with the`style.fontSmoothing` prop (see https://developers.recurly.com/reference/recurly-js/#common-field-style-properties) but that seems not to be working.

Thanks

**Comment by chrissrogers** [comment]
The Element will set `-webkit-font-smoothing: antialiased;` when `style.fontSmoothing: 'antialiased'` is passed. If you have a demo of the issue you're seeing, I would be happy to have a look and see what might be amiss. If you don't have one at present, I recommend [CodeSandbox](https://codesandbox.io/).

**Comment by aialec90** [comment]
Update:

It works with `style.fontSmoothing` but typescript complains about it:

`The expected type comes from property 'style' which is declared here on type 'IntrinsicAttributes & CardElementOptions & CommonElementProps<CardElementChangeEvent> & { ...; }'`

However, this can be ignored with `// @ts-ignore`
