### ISSUE TITLE
ThreeDSecureAction doesn't invoke onToken handler

### ISSUE THREAD

**Issue by IvanKrasilnikov** [recurly/react-recurly#111]
Hi there

When I test my app with help of 3DS2 Test Cards I can't get `three_d_secure_action_result_token_id` from invoking onToken handler at ThreeDSecureAction component. It looks like onToken just not invoking.

Code of my component:
```
const ThreeDSecurePromptComponent: React.FC<TProps> = ({
  actionToken,
}) => {
  const handleToken = useCallback(
    (token) => {
      // TODO: Show 3DS token id
      console.log(token.id)
    },
    [],
  )

  const handleError = useCallback((error) => {
    // TODO: Show 3DS error
    console.error(error)
  }, [])

  return actionToken ? (
    <div>
      <ThreeDSecureAction
        actionTokenId={actionToken}
        onToken={handleToken}
        onError={handleError}
      />
    </div>
  ) : null
}
```

Log after request 3ds:
![image](https://user-images.githubusercontent.com/14343785/107936350-983de180-6f93-11eb-9e40-3004208db718.png)

I can see the token in the answer of recurly request but can't get it inside onToken:

![image](https://user-images.githubusercontent.com/14343785/107936664-f4a10100-6f93-11eb-8750-373b0c9ae87f.png)

![image](https://user-images.githubusercontent.com/14343785/107936778-19957400-6f94-11eb-99b2-46d900475e37.png)

react-recurly 1.2.4
react 17.0.1
Google Chrome version 88.0.4324.150 (Official Build) (x86_64)
MacOS 11.1

**Comment by chrissrogers** [comment]
Hi @IvanKrasilnikov thanks for all of the detail you've provided here. I'd be happy to help track down what's happening. A couple of questions:

- Are you activating the "succeed" or "fail" option buttons in the test 3-D Secure frame? From your screenshot it appears the frame may not be large enough. The frame will grow to the dimensions of its container, so you can set the dimensions there. Clicking each button will call the respective callback `onToken` or `onError`, simulating customer outcomes.
- If that does not work, it may be work testing without the `useCallback` hook.

**Comment by IvanKrasilnikov** [comment]
Hi @chrissrogers, thanks for your response
With your help I've found my mistake - it was really related to iframe height. After fitting iframe height by his content I've found two buttons work as described in docs. useCallback doesn't affect this even.
Thank you very much! 👍
