### ISSUE TITLE
Month Select is too narrow on Safari

### ISSUE THREAD

**Issue by ayaniv** [recurly/react-recurly#112]
**Describe the bug**

![image](https://user-images.githubusercontent.com/1536123/108725969-92b23f80-752f-11eb-82f7-c22d7101ee66.png)

On safari, the clickzone of `CardMonthElement` where type=select is too narrow since safari cant set height on select.
Solution should be adding : `-webkit-appearance: none;` to the select.

**To Reproduce**
Open Safari, and go to here: 
https://recurly.github.io/react-recurly/?path=/docs/components-individual-card-elements-cardmonthelement--select
Try to click on the bottom part of the input and see that the drop down is not opened.

**Comment by chrissrogers** [comment]
@ayaniv thanks for this bug report! I can confirm this being present in Safari 14.0.2

**Comment by chrissrogers** [comment]
Thanks for the great resolution guidance. This fix will be made in our internal Element frame management library, and I'll update here when it's near release.

**Comment by ayaniv** [comment]
Thank you @chrissrogers looking forward

**Comment by chrissrogers** [comment]
@ayaniv we deployed this fix today. Thanks again for the report, and as ever don't hesitate to open issues.

**Comment by ayaniv** [comment]
You're the best ❤️
