### ISSUE TITLE
Safari - you need to click tab twice to move between input fields

### ISSUE THREAD

**Issue by ayaniv** [recurly/react-recurly#116]
**Describe the bug**

Go to the interactive demo using Safari:
https://recurly.github.io/react-recurly/?path=/docs/introduction-interactive-demo--page
On the right hand side, click on the **Card Number** input field under the **Individual Card Elements**.
Click on Tab. Nothing happens.
You have to click tab twice to move between the fields.
Only then, you can tab normally with one click in order to move between the input fields.

**Expected behavior**
It should work with 1 tab. just as it's working on Chrome.

**Comment by chrissrogers** [comment]
Hi @ayaniv! Unfortunately, this is a limitation of Safari itself that we have yet to have a workaround for. Safari's iframe security policy and behavior forces the frame to be focused prior to allowing programatic focus into an input wihtin the frame. We are still monitoring this, though, in the interest of establishing a workaround.

Thank you very much for your notes on the issue -- I'll add it to our internal tracking on this.

Closing for now, and I'll reach out with any updates in the future.

**Comment by apolunochev** [comment]
@chrissrogers tabbing between iframe-based inputs does work in Safari in this demo (for comparison) - https://checkout.stripe.dev/preview
