### ISSUE TITLE
MM/YY expiration date element

### ISSUE THREAD

**Issue by j10sanders** [recurly/react-recurly#118]
I'd like to use a single component for the expiration date, but not within the CardElement.  It looks like if I want the Expiration Date to be outside the CardElement, then I need to have two separate fields for Month and Year.  Do you have a solution for combining the two into a single component, like what you have on the CardElement?

**Comment by chrissrogers** [comment]
Hi @j10sanders -- I'd be happy to take this as a feature request for a `CardExpiryElement` to be created. The closest analogue now would be to use the separate `CardMonthElement` and `CardYearElement` and style them to appear as though they were one field. This would lack the automated cursor traverse from month to year as customers type, and I wouldn't recommend trying to programmatically move focus between them to simulate that. I might recommend sending off a quick email to support@recurly.com as well with your feature request!
