### ISSUE TITLE
Importing recurly via NPM

### ISSUE THREAD

**Issue by avivshafir** [recurly/react-recurly#134]
Give the possibility to import react-recurly via NPM and not via an HTML script tag.

**Comment by chrissrogers** [comment]
We only distribute Recurly.js via CDN and don't recommend lagging its most recent version. We do consider this option on a regular basis, but for now it will need to stick to CDN-only. [More info](https://developers.recurly.com/reference/recurly-js/index.html#self-hosting-recurlyjs)

Definitely appreciate the question. We'll continue to consider the option :]
