### ISSUE TITLE
The data-recurly attribute with third-party input components

### ISSUE THREAD

**Issue by Moeface** [recurly/react-recurly#146]
I'm working with a third-party select component (`react-select`), which does not allow custom attributes on the input that stores the value (See issue: https://github.com/JedWatson/react-select/issues/4239), which means that the `form` `ref` that `recurly.token` expects will not be able to find the value for the hidden input that the select is using to store the value of the select.

Is there a way around this?

It would be great if you could choose to pass in the billing fields yourself, without having to rely on the `form` `ref` and `data-recurly`.

Any assistance would be greatly appreciated.

**Comment by chrissrogers** [comment]
No problem. It's possible to call `recurly.token` with an Object specifying the billing fields instead of an `HTMLFormElement`. Here's a reference that you can use: https://github.com/recurly/recurly-js/blob/master/lib/recurly/token.js#L60-L71

**Comment by Moeface** [comment]
Ah excellent, I should have checked the source 😅 

Thanks for your help!
