### ISSUE TITLE
Support React 17 in typings

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [recurly/react-recurly#158]
_Warning_: Github issues are not an official support channel for Recurly. If you have an urgent request we suggest you contact us through an official channel: support@recurly.com or https://support.recurly.com

**Describe the bug**

`@recurly/react-recurly@1.2.4` has a dependency on `@types/react@^16.9.32`. I'd like to use it with React@17... and soon, React@18.

**To Reproduce**

In an project:

```
yarn add @recurly/react-recurly
yarn add @types/react@17 -D
npx yarn-deduplicate
```

**Expected behavior**

Just one `@types/react`. `@recurly/react-recurly` should have a range either like:

* `>=16.9.32`: if you're ok assuming v17 and onward are compatible
* `^16.9.32 || ^17` if just v17 is in target

Per https://reactjs.org/blog/2020/08/10/react-v17-rc.html#other-breaking-changes and my local testing it seems like v17 is fully supported.

Note that you can use [yarn resolutions](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions) as a workaround, but it'd be better to not have to. 

**Your Environment**

- Which version of react-recurly are you using? `@recurly/react-recurly@1.2.4`
- Which version of react are you using? `17.0.2`
- Which browser (+version) are you using? N/A

**Comment by chrissrogers** [comment]
We're still awaiting support for some of our testing dependencies (enzyme) before we can fully support react 17, or else a plan to migrate to another stubbing framework.

**Comment by JoshuaKGoldberg** [comment]
👋 Thanks for the response @chrissrogers!

If you don't mind me asking, could you provide a little more info on what the blocker is for _typings_ support? There isn't anything I can find that would stop react-recurly from being used in a React 17 app.
