### ISSUE TITLE
Update packages

### ISSUE THREAD

**Issue by sgehrman** [recurly/react-recurly#163]
@types/react                             ^16.9.32  →  ^17.0.38     
 lodash                                   ^4.17.15  →  ^4.17.21     
 memoize-one                                ^5.1.1  →    ^6.0.0     
 prop-types                                ^15.7.2  →   ^15.8.1     
 @babel/cli                                 ^7.8.4  →   ^7.16.8     
 @babel/core                                ^7.9.6  →  ^7.16.10     
 @babel/plugin-proposal-class-properties    ^7.8.3  →   ^7.16.7     
 @babel/preset-env                          ^7.9.6  →  ^7.16.10     
 @babel/preset-react                        ^7.9.4  →   ^7.16.7     
 @koa/cors                                  ^3.0.0  →    ^3.1.0     
 @storybook/addon-actions                  ^5.3.18  →   ^6.4.13     
 @storybook/addon-docs                     ^5.3.18  →   ^6.4.13     
 @storybook/addon-viewport                 ^5.3.18  →   ^6.4.13     
 @storybook/addons                         ^5.3.18  →   ^6.4.13     
 @storybook/react                          ^5.3.18  →   ^6.4.13     
 @testing-library/react-hooks               ^3.2.1  →    ^7.0.2     
 babel-loader                               ^8.1.0  →    ^8.2.3     
 coveralls                                  ^3.1.0  →    ^3.1.1     
 dtslint                                    ^3.5.1  →    ^4.2.1     
 enzyme-adapter-react-16                   ^1.15.2  →   ^1.15.6     
 jest                                      ^25.5.3  →   ^27.4.7     
 jest-extended                             ^0.11.5  →    ^1.2.0     
 jest-transform-css                         ^2.0.0  →    ^3.0.0     
 koa                                       ^2.11.0  →   ^2.13.4     
 koa-better-http-proxy                      ^0.2.4  →    ^0.2.9     
 koa-bodyparser                             ^4.2.1  →    ^4.3.0     
 koa-send                                   ^5.0.0  →    ^5.0.1     
 react                                    ^16.13.1  →   ^17.0.2     
 react-dom                                ^16.13.1  →   ^17.0.2     
 react-test-renderer                      ^16.13.1  →   ^17.0.2     
 regenerator-runtime                       ^0.13.5  →   ^0.13.9

**Comment by chrissrogers** [comment]
Thanks. We'll continually have a look at our development package updates
