### ISSUE TITLE
Getting Uncaught TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by berkerdemirer** [recurly/react-recurly#17]
As soon as I add RecurlyProvider to my code it fails to load whole page. I bet this is caused by some webpack config but couldn't find out the reason. Any help?

**Comment by chrissrogers** [comment]
@berkerdemirer -- happy to help. Do you have a full stacktrace you could share, or a jsfiddle that will reproduce the issue?

**Comment by berkerdemirer** [comment]
I couldn't able to reproduce the issue with CRA but I still have it on our service. I tried to compare the both app and differences are mainly based on webpack version and config. Our project uses webpack3 atm while CRA uses webpack4. I can try to show you the trace.


`vendors.js:713 Uncaught TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (vendors.js:713)
    at fn (vendors.js:118)
    at Object.1400 (index.js:7069)
    at __webpack_require__ (vendors.js:713)
    at fn (vendors.js:118)
    at Object.1325 (index.js:85)
    at __webpack_require__ (vendors.js:713)
    at fn (vendors.js:118)
    at Object.223 (App.js:1)
    at __webpack_require__ (vendors.js:713)`

My guess is that the following import doesn't return anything

`/* harmony import */ var __WEBPACK_IMPORTED_MODULE_14__recurly_react_recurly__ = __webpack_require__(1408);`

**Comment by dbrudner** [comment]
I tried to reproduce the issue using webpack 3.12.0, but didn't find any errors https://github.com/dbrudner/react-recurly-webpack-3.

There's not much else we can without a reproduction of the issue or more information. I'm closing this for now pending more information. Thanks for reporting, please let us know if there's anything else we can assist with.

**Comment by chrissrogers** [comment]
Given the trace, I do think it will likely come down to a webpack issue. There are a number of issues that cite similar errors with a variety of potential causes. Here are two prominent ones:

1: https://github.com/webpack/webpack/issues/959
2: https://github.com/webpack/webpack/issues/6094

**Comment by jiangxiaoqiang** [comment]
did any one find a solution to solve this problem? https://stackoverflow.com/questions/70728473/uncaught-typeerror-cannot-read-properties-of-undefined-reading-call-when-up
