### ISSUE TITLE
React 18

### ISSUE THREAD

**Issue by Achaak** [recurly/react-recurly#175]
**Describe the bug**

Hi, 
I just updated React to version 18 and this error appeared.
It seems that react-recurly must be upgraded to React 18 for this to build.

![image](https://user-images.githubusercontent.com/39270779/162776232-5da8f79e-4fc5-4378-afb8-27c620f5f920.png)

**To Reproduce**

Upgrade react to version 18

**Expected behavior**

**Your Environment**

- Which version of react-recurly are you using?
1.2.4
- Which version of react are you using?
18.0.0

**Comment by AlexanderVishnevsky** [comment]
⚠️ It will appear with any React 18 version.

Just update types this:

```
export const RecurlyProvider: React.FC<RecurlyOptions>;

export const Elements: React.FC<ElementsProps>;
```

**Example:**

Before
```
import React from 'react';

const Component: React.FC = ({children}) => {...}
```

After
```
import React from 'react';

const Component: React.FC<React.PropsWithChildren> = ({children}) => {...}
```

**Comment by AlexanderVishnevsky** [comment]
💡 temporary solution for developers:
downgrade `@types/react` dependency to latest 17 major release version

Example:
```
"@types/react": "^17.0.50"
````
