### ISSUE TITLE
RecurlyProvider and Elements missing children prop

### ISSUE THREAD

**Issue by angrycat9000** [recurly/react-recurly#204]
**Describe the bug**

The typings for RecurlyProvider and Elements do not include a `children` attribute.  This results in typescript errors like:

> src/features/billing/RecurlyFormWrapper.tsx:17:6 - error TS2322: Type '{ children: Element; publicKey: string; }' is not assignable to type 'IntrinsicAttributes & RecurlyOptions'.
  Property 'children' does not exist on type 'IntrinsicAttributes & RecurlyOptions'.
>
> 17     &lt;RecurlyProvider publicKey={billingKey}&gt;

**To Reproduce**

**Expected behavior**

No error is shown when using 
```jsx
<RecurlyProvider>
  <Elements>
    <form>...</form>
  </Elements>
</RecurlyProvider>
```

**Your Environment**

- Which version of react-recurly are you using? 1.2.7
- Which version of react are you using? 18.2.0
- Which browser (+version) are you using?

**Comment by artyom-88** [comment]
I've created a fix PR https://github.com/recurly/react-recurly/pull/205

**Comment by angrycat9000** [comment]
Looking forward to the next release with this fix in it.  

Right now have to work around it with several ignore comments.

```jsx
{/* eslint-disable-next-line @typescript-eslint/ban-ts-comment */}
{/* @ts-ignore */}
<RecurlyProvider publicKey={billingKey}>
  {/* eslint-disable-next-line @typescript-eslint/ban-ts-comment */}
  {/* @ts-ignore */}
  <Elements>{children}</Elements>
</RecurlyProvider>
```

**Comment by jsakas** [comment]
It looks like this is merged two months ago, are we getting a release with the fix soon?
