### ISSUE TITLE
Ineractive Demo page not working properly

### ISSUE THREAD

**Issue by chrisdeely** [recurly/react-recurly#219]
**Describe the bug**

The `Interactive Demo` linked from the README and Storybook site is no longer operational. The CodeSandbox startup complains during installation of the dependencies, failing on loading of the react-recurly library.

**To Reproduce**

Open the [link from the documentation](https://recurly.github.io/react-recurly/?path=/docs/introduction-interactive-demo--page)

Notice the failure logged on the right side:
<img width="598" alt="Screenshot 2023-10-04 at 5 10 05 PM" src="https://github.com/recurly/react-recurly/assets/230378/c9e29fcb-a6b7-411b-8747-3da26cb9de93">

> Error
Could not fetch dependencies, please try again in a couple seconds: Could not fetch https://cdn.jsdelivr.net/gh/github:recurly/react-recurly/package.json

Following the jsdelivr link from the error provides the message: `Invalid URL. The URL structure is /gh/user/repo@version/file.js`

The format of the dependency within `demo/package.json` includes a `github:` qualifier, which appears to cause the issue:
`"@recurly/react-recurly": "github:recurly/react-recurly",`

Removing the prefix appears to get the dependency to install, but then you are left with a blank page which does not initialize the React app.

**Expected behavior**

The dependencies should install and initiate the Sandbox

**Your Environment**

- Which version of react-recurly are you using?  N/A
- Which version of react are you using?  N/A
- Which browser (+version) are you using? Chrome MacOS 117

**Comment by chrisdeely** [comment]
@chrissrogers @douglasmiller Thanks for the speedy responses. Unfortunately, the demo site now seems more broken than before.

The [CodeSandbox](https://codesandbox.io/embed/github/recurly/react-recurly/tree/main/demo?autoresize=1&fontsize=12&hidenavigation=1&theme=light) instance is working properly.

The [Storybook](https://recurly.github.io/react-recurly/?path=/docs/introduction-getting-started--docs) site is failing with the following error:
```
TypeError: Failed to fetch dynamically imported module: https://recurly.github.io/react-recurly/assets/config-944b7ede.js
```

Is there a build step which needs to be run in order to publish an update there?

**Comment by douglasmiller** [comment]
@chrisdeely There was an issue with storybook not properly publishing to github pages. I've got a PR open to fix this (and the links in the README that have updated). 

The storybook site should be working now though.
