### ISSUE TITLE
`this.context` is undefined in `ThreeDSecureAction`

### ISSUE THREAD

**Issue by Silviu-Marian** [recurly/react-recurly#223]
[it's referencing `this.context` in the constructor, despite performing an earlier check a few lines above for `context` passed as constructor argument](https://github.com/recurly/react-recurly/blob/v1.2.7/lib/three-d-secure-action.js#L66)

**To Reproduce**

Simply utilize that component.

**Expected behavior**

Do not throw.

**Your Environment**

-  @recurly/react-recurly@1.2.6
- react@16.14.0
- Latest Chrome

**Comment by chrissrogers** [comment]
I think I'd like to learn a bit more about how this occurs. We'd normally expect the `PureComponent` constructor to assign that value ([see src](https://github.com/facebook/react/blob/v16.14.0/packages/react/src/ReactBaseClasses.js#L131)). I think it's safe to assume that you're rendering the component within a RecurlyContext.

**Comment by chrissrogers** [comment]
I see! Yes, that makes sense.

We have a couple other places where `this.context` is relied on, one of which is outside of the constructor, so I think any approach other than implementing contexts in preact's `PureComponent` would have to be treated as a patch..

If you're willing to make that request of preact, then I think that's a great idea. That would address all of these cases, and those in any other library, in the most 'correct' way. We can consider ways to patch it in react-recurly, but I'm also somewhat concerned about any other potential compatibility issues that may exist between the APIs.
