### ISSUE TITLE
Any plans on adding typescript typings?

### ISSUE THREAD

**Issue by ashokdudhade-cbs** [recurly/react-recurly#37]

**Comment by dbrudner** [comment]
Great question! We're currently working towards releasing typescript definitions for recurly-js. Once this is released, we can start working on creating typescript support for react-recurly. There's no specific timeline for either of these releases right now, but know that we're working hard to get this done!

**Comment by mrtheyann** [comment]
Can relate.
Typings are extremely anticipated.

**Comment by codymoorhouse** [comment]
Also hoping this becomes live 👍

**Comment by elliotbonneville** [comment]
Is there anything I can do to help drive this process forward?

**Comment by dbrudner** [comment]
@elliotbonneville As mentioned, we're actively working on typescript support for recurly-js right now and should begin working on types for react-recurly after that. If you'd like to help, we'll need feedback from early-adopters after they're published and would love to hear from you then.

I'll make sure to post in this thread with info regarding our progress and keep all participants informed.

**Comment by dbrudner** [comment]
Quick update @elliotbonneville or anyone else in this thread:

If anyone would like to go ahead and begin work on creating typescript definitions for react-recurly, please feel welcome to do so!

If it helps, the types that we're working on for recurly-js can be found and used for reference in this PR https://github.com/recurly/recurly-js/pull/584

If needed, I'm more than willing to provide support or assistance for this.

**Comment by chrissrogers** [comment]
If anyone would like to follow along, we have submitted our type definitions to DefinitelyTyped here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43398

**Comment by dbrudner** [comment]
Happy to share that with the release of react-recurly [v1.2.1](https://github.com/recurly/react-recurly/releases/tag/v1.2.1), we now have types for this library.

We're open to any and all feedback on the types themselves. If you find anything broken or that you think needs to be changed, feel free to open an issue or PR.

Thanks for your patience and for communicating this need! 👍
