### ISSUE TITLE
Electron Support with PayPal

### ISSUE THREAD

**Issue by Mootook** [recurly/react-recurly#44]
Hello, my team and I are building an app using react-recurly and electronJS.

We've run into problems integrating paypal in the electron app through recurlyJs's paypal api.
Mainly that the paypal listeners such as on 'token', 'cancel', 'error' do not seem to be firing.

The snippet below runs when a button is clicked

        window.recurly.configure('API_KEY')

        const paypal = window.recurly.PayPal({
          display: {
            displayName: 'Test',
            description: 'Test description'
          }
        })
        paypal.on('error', error => {
          console.error(error)
        })

        paypal.on('token', token => {
          console.log('Token: ',  token)
        })
  
        paypal.on('cancel', () => {
          console.log('Cancelled')
        })
  
        paypal.on('ready', () => {
          console.log('Ready')
        })

        paypal.start()
I am running react 16.12.0 and react-recurly 1.0.2.

Notes: Token listener fires if snippet is run in browser.

Thank you for any help.

**Comment by dbrudner** [comment]
I was able to create an electron app using react-recurly that successfully implements a paypal flow: https://github.com/dbrudner/rjs-electron-example (`yarn install`, then `yarn dev` to run).

Without seeing a reproduction, my best guess is this is an issue with logging in electron.

Feel free to respond if the example I shared doesn't work or if you have any other concerns. Thanks!

**Comment by dbrudner** [comment]
Also, if you would be open to sharing, I'd love to hear about your use-case for using recurly with electron!

**Comment by Mootook** [comment]
@dbrudner Thanks for the demo project! Turns out I had a custom lister on the 'new-window' event in the main window's process. I was preventing default behavior and attempting to create my own browser window. https://www.electronjs.org/docs/api/web-contents
Also, we are using react-recurly as the basis for our in-app purchases. [Our app](https://kast.gg/)
Thanks again for the help!

**Comment by dbrudner** [comment]
For anyone who might come across this issue, we now fully support [recurly.js with electron](https://developers.recurly.com/reference/recurly-js/index.html#support)
