### ISSUE TITLE
Are the additional form fields like address1 and city PCI compliant?

### ISSUE THREAD

**Issue by etiennemarais** [recurly/react-recurly#45]
## Summary

We implement RecurlyJS using the examples from this react library. I am noticing that only the `CardElement` wraps in an iframe but not these fields when sending to get tokenized:

- `first_name`
- `last_name`
- `address1`
- `address2`
- `city`
- `country`
- `state`
- `postal_code`

as per your official documentation:

```
// my-payment-form.js
import React from 'react';
import { CardElement } from '@recurly/react-recurly';

export function MyPaymentForm (props) {
  return (
    <form>
      <input type="text" data-recurly="first_name" placeholder="First name" />
      <input type="text" data-recurly="last_name" placeholder="Last name" />
      <CardElement />
    </form>
  );
}
```

I wanted to find out if those fields are still safe when they `POST` to the recurly token api?

**Comment by dbrudner** [comment]
Yup, this looks good to me according to our docs. Billing fields aren't hosted, but should be safe to send data from in your request.
