### ISSUE TITLE
Configure CVV required

### ISSUE THREAD

**Issue by yevhen-logosha** [recurly/react-recurly#63]
Greetings!
Is it possible to configure recurly to make CVV(and `postal_code`) field required, so it is being validated upon submission too?
Many thanks in advance.

`"@recurly/react-recurly": "1.1.2"`

**Comment by yevhen-logosha** [comment]
Got it, so passing `required={['cvv'])` to `RecurlyProvider` did the trick.
Would be great to add things like that to docs

**Comment by dbrudner** [comment]
Totally agree, this looks like a gap in our current documentation. We'll be looking to add something, thank you for reporting and nice job resolving the issue yourself.

**Comment by dbrudner** [comment]
The docs for react-recurly have been updated to include all available props for `<RecurlyProvider />` https://recurly.github.io/react-recurly/?path=/docs/components-recurlyprovider--page

Thanks again for reporting this!
