### ISSUE TITLE
Safari:  Credit Card Form - Unable to tab to next field

### ISSUE THREAD

**Issue by lenota** [recurly/react-recurly#90]
**Describe the bug**

This bug reproduced only in Safari! (In chrome works fine)
User should click tab button 3 times to navigate between credit card number/cvc/month/year fields.
After successful navigation it works fine.

**To Reproduce**
I use following structure 

`<StyledLabel htmlFor="number">
              Card Number*
              <CardNumberElement
                id="number"
              />
            </StyledLabel>
             <StyledLabel htmlFor="month">
                Expiration Month*
                <CardMonthElement
                  id="month"
                />
              </StyledLabel>
              <StyledLabel htmlFor="year">
                Expiration Year*
                <CardYearElement
                  id="year"
                />
              </StyledLabel>
            <StyledCVVSection>
              <StyledLabel htmlFor="CVV">
                CVV*
                <CardCvvElement
                  id="CVV"
                />
              </StyledLabel>
`

I checked this issue and see that for first time when user click tab - then `<input type="text" style="position: static; top: 0px; left: -1000px; opacity: 1; background-color: red;" aria-hidden="true">` these fields are focused!
**Expected behavior**

Navigation with tab button should work. 

**Your Environment**

Safari version: Version 13.1.1 (15609.2.9.1.2),  
@recurly/react-recurly :  ^1.2.2
react: ^16.8.6

**Comment by chrissrogers** [comment]
This may be related to https://github.com/recurly/recurly-js/pull/618

**Comment by chrissrogers** [comment]
Just a note that Safari on desktop and iOS has some restrictions around focusing within iframes. In some circumstances, it's necessary for the user to focus into the iframe first before an Element within the iframe can be programmatically focused. We are looking into a workaround for this on Safari desktop. Some of the odd behavior will be addressed in the upcoming release of Recurly.js `v4.14.0`, though.

**Comment by chrissrogers** [comment]
Mind testing it now? `v4.14.0` has been released.

**Comment by lenota** [comment]
Tested with recurly v4.14.0 & @recurly/react-recurly: ^1.2.2
Still reproduced: i need to click tab twice (before it was 3 times to navigate) for navigate to next input. 
FYI:
Also i see that hidden fields like`<input type="text" style="position: static; top: 0px; left: -1000px; opacity: 1; background-color: red;" aria-hidden="true">` which i mentioned before disappeared from DOM.

**Comment by chrissrogers** [comment]
The disappearance of that HTMLInputElement from the DOM is expected in the new release, which is good to hear.

The behavior we see in Safari now is that, on first tabbing procession, the tabbing behavior will move focus to the next iframe first before proceeding to the HTMLInputElement within the iframe. I'll update here with anything we discover in order to work around this behavior.

**Comment by chrissrogers** [comment]
We're still seeing this behavior on Safari, and as yet are exploring workarounds. Safari simply differs in the way it allows tabbing progression with regard to cross-domain iframes. Since this isn't an issue specific to react-recurly, I'm going to close this issue, but we'll continue to track this.
