### ISSUE TITLE
Cannot change stylings to individual card elements

### ISSUE THREAD

**Issue by albertngo1** [recurly/react-recurly#98]
_Warning_: Github issues are not an official support channel for Recurly. If you have an urgent request we suggest you contact us through an official channel: support@recurly.com or https://support.recurly.com

**Describe the bug**

The [original docs](https://developers.recurly.com/reference/recurly-js/#css-classes) says that elements can be manipulated to present an iframe that's more in line with our app's presentation. However, in [react-recurly's interactive demo](https://recurly.github.io/react-recurly/?path=/docs/introduction-interactive-demo--page), while I'm able to apply stylings to the card element, any css changes made to the individual pieces do not take effect.

**To Reproduce**

Go to the sandbox, add styling to an individual element's css (eg. `recurly-element-card-number`), refresh to see that it doesn't change.

Or visit https://codesandbox.io/s/friendly-firefly-l1nuh?file=/public/index.html for random checks that I've done.

**Expected behavior**

Stylings are injected into the resulting iframes.

**Your Environment**

- Which version of react-recurly are you using?
`^1.2.2`
- Which version of react are you using?
`16.13.1`
- Which browser (+version) are you using?
` 85.0.4183.102 (Official Build) (64-bit)`

**Comment by chrissrogers** [comment]
Thanks for reporting this! The documentation had an error in it -- the class names are:

`recurly-element-number`, `recurly-element-month`, `recurly-element-year`, and `recurly-element-cvv`.

We'll be updating the documentation shortly. Cheers!
